#!/bin/bash
SCRIPT=/raid/haotian/Projects/lift3d/external/hybrik/infer_video.py 
VIDEO_DIR=/raid/jhong/tennis-video
TRACK_DIR=/home/james/lift3d/data/tennis_track
OUT_DIR=/raid/haotian/Projects/lift3d/output/tennis_pose_hybrik

CUDA_VISIBLE_DEVICES=2 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 0 18 & 
CUDA_VISIBLE_DEVICES=2 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 1 18 & 
CUDA_VISIBLE_DEVICES=2 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 2 18 & 

CUDA_VISIBLE_DEVICES=3 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 3 18 & 
CUDA_VISIBLE_DEVICES=3 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 4 18 & 
CUDA_VISIBLE_DEVICES=3 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 5 18 & 

CUDA_VISIBLE_DEVICES=4 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 6 18 & 
CUDA_VISIBLE_DEVICES=4 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 7 18 & 
CUDA_VISIBLE_DEVICES=4 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 8 18 & 

CUDA_VISIBLE_DEVICES=5 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 9 18 & 
CUDA_VISIBLE_DEVICES=5 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 10 18 & 
CUDA_VISIBLE_DEVICES=5 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 11 18 & 

CUDA_VISIBLE_DEVICES=6 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 12 18 & 
CUDA_VISIBLE_DEVICES=6 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 13 18 & 
CUDA_VISIBLE_DEVICES=6 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 14 18 & 

CUDA_VISIBLE_DEVICES=7 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 15 18 & 
CUDA_VISIBLE_DEVICES=7 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 16 18 & 
CUDA_VISIBLE_DEVICES=7 python $SCRIPT $VIDEO_DIR $TRACK_DIR $OUT_DIR --part 17 18 &